version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    env_file:
      - .env
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 3000:3000
    links:
      - postgres
      - redis

  postgres:
    image: postgres:13.4
    container_name: app-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRESQL_ROOT_USER:-postgres}
      - POSTGRES_DB=${POSTGRESQL_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres

  redis:
    container_name: app-redis
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
